### ISSUE TITLE
Is this just for PTP?

### ISSUE THREAD

**Issue by JoeMurray** [jmcclelland/net.ourpowerbase.report.advancedfundraising#1]
The name in the extensions page for this extension is 'Advanced Fundraising Reports for PTP'. Does this depend on anything in PowerBase, or is it usable by the community? (BTW, I think it would be better to take branding out of title.)

**Comment by jmcclelland** [comment]
Yes - agreed. Just removed it. That was left over from the version Eileen created for us. It should be useable for other groups as well.
