### ISSUE TITLE
download url

### ISSUE THREAD

**Issue by JoeMurray** [jmcclelland/net.ourpowerbase.report.advancedfundraising#2]
When trying to install into a 4.4 site, I get an error:

Extension Upgrade Failed
Download failed - ZIP file is unavailable or malformed

Looking into a bit, I see that the download url https://github.com/jmcclelland/net.ourpowerbase.report.advancedfundrai/archive/v1.0.3.zip is created based on the assumption that there is a zip file like that. However, it seems there is a truncation of the name of the extension from fundraising to fundrai.

**Comment by jmcclelland** [comment]
I think that URL is generated automatically by the CiviCRM infrastructure. I'll ping Tim to see if there is any length limits that are being hit.

**Comment by jmcclelland** [comment]
I manually fixed the link on verson 1.0.3 (https://civicrm.org/extensions/advanced-fundraising-reports/version-103) but it is still visible on the link for version 1.0.2 (https://civicrm.org/extensions/advanced-fundraising-reports/102)

**Comment by JoeMurray** [comment]
That'll be fine. I unstalled manually yesterday.

**Comment by totten** [comment]
There's a bug where the scanner (which looks for tags and generates releases) made a hard-coded assumption that Github URLs ended with ".git" (and blindly removed the last four characters). I've patched and released, but we don't have a very good test harness, so we'll have to wait and see if it works correctly on the next release.

**Comment by jmcclelland** [comment]
Thanks Tim! I'll assume it's fixed (and in any event, the current release _is_ fixed) and re-open if the next release doesn't work.
