### ISSUE TITLE
Latest release v1.0.5 contains a template override

### ISSUE THREAD

**Issue by konadave** [jmcclelland/net.ourpowerbase.report.advancedfundraising#7]
I'm the author/maintainer of https://github.com/konadave/com.klangsoft.overrides which I just released a beta for a new, smarter, 2.0 version. The very first IRL client site I've tested on has had their system status set to critical because the latest release of this extension (`advancedfundraising`) overrides a template file that has since been modified by CiviCRM.

v1.0.5 was released many years ago and many commits have taken place since. There is no longer a template override.

Could you please create a new release based on `master`?

The new version is smarter and automated, but hardly anybody knows about it yet. Once I move off beta and people start upgrading, you'll probably start getting more requests for this.

Thanks.

**Comment by jmcclelland** [comment]
Thanks for the tip. I just tagged a release. It should go out tomorrow.

**Comment by konadave** [comment]
Thanks.
